### ISSUE TITLE
Colliding async routes don't work as expected

### ISSUE THREAD

**Issue by MattIPv4** [honojs/hono#258]
👋 If you have two synchronous routes that overlap as I'd expect:

```js
app.get('/a', c => c.text('a'));
app.get('/:slug', c.text('slug'));
```

Requesting `/a` returns `a`, and requesting `/b` returns `slug`.

However, if these routes are asynchronous, then things don't behave correctly:

```js
app.get('/a', async c => {
    await new Promise(resolve => setTimeout(resolve, 10));
    return c.text('a');
});
app.get('/:slug', async c => {
    await new Promise(resolve => setTimeout(resolve, 10));
    return c.text('slug');
});
```

Requesting either `/a` or `/b` results in `slug` being returned. Would be great to see this fixed so that there is a deterministic priority for route matching that is consistent.

**Comment by MattIPv4** [comment]
Fwiw, it looks like this can be worked around for now by doing something like this:

```js
app.get('/a', async c => {
    await new Promise(resolve => setTimeout(resolve, 10));
    return c.text('a');
});
app.get('/:slug', async (c, next) => {
    if (c.req.param('slug') === 'a') {
        await next();
        return;
    }
    await new Promise(resolve => setTimeout(resolve, 10));
    return c.text('slug');
});
```

But, it'd still be great to have this solved in the lib itself. Cheers :)

**Comment by yusukebe** [comment]
Hi @MattIPv4 !

It's a bug, I've fixed it in PR #259 .  This bug fix will be included next release.
Thank you.

**Comment by MattIPv4** [comment]
Thank you! 💙

**Comment by MattIPv4** [comment]
👋 Hey @yusukebe, I just pulled down the latest release, and it seems that this is partially fixed, but not fully. There seems to be some pollution going on between handlers, and both handlers seem to be invoked.

Taking an example of:


```js
app.get('/a', async c => {
    console.log('a');
    await new Promise(resolve => setTimeout(resolve, 10));
    return c.text('a');
});
app.get('/:slug', async c => {
    console.log('slug');
    await new Promise(resolve => setTimeout(resolve, 10));
    c.status(404);
    return c.text('slug');
});
```

If I make a request to `/a`, I do now get back the text `a`, but the status code is `404` -- polluted by the `/:slug` handler.

If I then look in console, I see both `a` and `slug` logged, so it seems like both handlers are being invoked (with `/:slug` being invoked first).

**Comment by yusukebe** [comment]
Hi @MattIPv4 

Actually, the behavior that both handlers are invoked is **expected**. So,

> If I then look in console, I see both slug and a logged

That is not wrong. Because all handlers are treated as Middleware. Every handlers are called, and only one of the Response returned from the handlers will be used for the end user. 

It's in the specifications.

**BUT**, I notice that this design is not good. In this case, only one handler should be processed, console.log should emit only `a`.

I'll consider about it. Thank you!

**Comment by yusukebe** [comment]
@MattIPv4 

Hi! We've released v1.4.0.
https://github.com/honojs/hono/releases/tag/v1.4.0

In this release, this issue may be fixed. Check it out.

**Comment by MattIPv4** [comment]
Just bumped and can confirm this is now behaving in a far more intuitive way to me (first handler that returns stops the chain)! Tyvm!
