### ISSUE TITLE
[Workers] [WebSocket Helper] Error after disconnecting when client sent a message

### ISSUE THREAD

**Issue by JustJoostNL** [honojs/hono#4603]
### What version of Hono are you using?

4.11.3

### What runtime/platform is your app running on? (with version if possible)

Cloudflare Workers

### What steps can reproduce the bug?

```ts
hono.get(
  "/ws",
  upgradeWebSocket((c) => ({
    onMessage: async (ev: MessageEvent, ws) => {
      ws.send("hi");
    },
  })),
);
```

1. Connect to the websocket.
2. Send a message to the server as client.
3. Observe the `hi` response.
4. Disconnect the websocket.
5. Observe the Cloudflare Workers error: `Uncaught Error: The Workers runtime canceled this request because it detected that your Worker's code had hung and would never generate a response. Refer to: https://developers.cloudflare.com/workers/observability/errors/`.

### What is the expected behavior?

When disconnecting after sending a message it should not show that error. Interestingly, when connecting, and disconnecting right after without sending a message, it works fine.

### What do you see instead?

The following unexpected Cloudflare Workers error: `Uncaught Error: The Workers runtime canceled this request because it detected that your Worker's code had hung and would never generate a response. Refer to: https://developers.cloudflare.com/workers/observability/errors/`.

**Comment by JustJoostNL** [comment]
This was actually my bad, and I solved this by adding the following to the upgrade helper:

```ts
onClose: (_ev, ws) => {
  ws.close();
},
```

**Comment by JustJoostNL** [comment]
I'm afraid I have to reopen this, calling `ws.close()` only solved this in local development with Wrangler. When using the `--remote` option or when deploying this, this actually caused a second "hanging error". After removing the `ws.close()` again, it went back to only a single "hanging error", both locally and remote/deployed.

What's wrong here?

**Comment by gogogoghost** [comment]
Same issue

**Comment by toreis-up** [comment]
Hi, I ran into the same problem.
It might be related to Workers issue.

Reproduction is available in [here (Hono repro)](https://github.com/toreis-up/honojs-hono-4603) and [here (Workers Script repro)](https://github.com/toreis-up/honojs-hono-4603-workers)

**Comment by 04041b** [comment]
same issue here 👍

**Comment by JustJoostNL** [comment]
@yusukebe Any news on this? It's quite an important thing to have solved.

**Comment by yusukebe** [comment]
This issue has been resolved in the Workers runtime.

Cloudflare introduced the [web_socket_auto_reply_to_close compatibility flag](https://developers.cloudflare.com/workers/configuration/compatibility-flags/#websocket-auto-reply-to-close), which is enabled by default for Workers with a compatibility date of `2026-04-07` or later. With this flag, the runtime automatically replies to the client's Close frame, so the "code had hung" error no longer occurs.

Since the runtime now handles this, we won't add a workaround in Hono for older compatibility dates. Closing.

**Comment by JustJoostNL** [comment]
@yusukebe I have updated the compatibility date and the issue is still present:

```
✘ [ERROR] Error: The Workers runtime canceled this request because it detected that your Worker's code had hung and would never generate a response. Refer to: https://developers.cloudflare.com/workers/observability/errors/
```

**Comment by yusukebe** [comment]
@JustJoostNL 

I can't reproduce it. Can you upgrade your wrangler and try it again?

**Comment by JustJoostNL** [comment]
```sh
bunx wrangler --version

⛅️ wrangler 4.124.0
```

@yusukebe Yes, it's the latest version. It only seems to happen after sending a message from the client over the websocket connection.

**Comment by yusukebe** [comment]
@JustJoostNL Could you share a minimal reproduction repository?

**Comment by JustJoostNL** [comment]
@yusukebe Yup! https://github.com/JustJoostNL/honorepro

**Comment by yusukebe** [comment]
@JustJoostNL 

Thanks for the repro! I ran it locally and also deployed it to production. Here is what I found:

- If the client closes the connection normally (`ws.close()`), there is no error.
- The error only happens when the client disconnects without sending a Close frame (for example, killing the client process).
- This error only appears in local `wrangler dev`. In production, the request just becomes "Canceled"; no error is thrown.

So this is not something Hono can fix. It also happens with a raw `WebSocketPair` without Hono. It is just log noise from the local dev runtime.

**Comment by JustJoostNL** [comment]
@yusukebe, this also happens for me in production deployment to Cloudflare. When using `wrangler tail` to see the live logs I'm seeing the same error:

```
✘ [ERROR] Error: The Workers runtime canceled this request because it detected that your Worker's code had hung and would never generate a response. Refer to: https://developers.cloudflare.com/workers/observability/errors/
```

**Comment by yusukebe** [comment]
@JustJoostNL 

I can't reproduce it. I deployed your repro to production and confirmed there is no error. Normal close is clean, and even an abrupt disconnect only shows "Canceled" with no thrown error.
